# Generated by Django 4.2.6 on 2023-11-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_delete_student_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
    ]
