# Generated by Django 4.2.6 on 2023-11-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=30)),
                ('review', models.CharField(max_length=30)),
            ],
        ),
    ]
