# Generated by Django 4.2.6 on 2023-11-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
            ],
        ),
    ]
