# Generated by Django 4.2.6 on 2023-12-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
